data_config:
  batch_size: 32 
  max_side: 256 
  num_bins: 256 
  max_objects: 20
  data_dir: "~/data"
model:
  name: "resnet50v2"
  num_layers: 4
  d_model: 128
  num_heads: 8
  d_ff: 512
  #target_vocab_size: 260
  attention_dropout_rate: 0.1
  ff_dropout_rate: 0.1
training:
  learning_rate: 1e-4
  epochs: 100 
