data_config:
  batch_size: 2 
  max_side: 256 
  num_bins: 256 
  max_objects: 20
  data_dir: "~/data"
model:
  name: "resnet50v2"
  num_layers: 4
  d_model: 128
  num_heads: 8
  d_ff: 512
  attention_dropout_rate: 0.1
  ff_dropout_rate: 0.1
training:
  initial_learning_rate: 1e-3 
  warmup_epochs: 10
  epochs: 2000 
  steps_per_epoch: 20 

checkpoint:  pix2seq.weighwts
checkpoint_output_dir: pix2seq.weights
